spring:
  application:
    name: opticlingo

  # --- Configuracion Base de datos ---
  datasource:
    url: jdbc:postgresql://72.62.169.13:5432/opticlingo_db?currentSchema=core
    username: devnexuslabs_admin
    password: 0pt1cl1ng0@
    driver-class-name: org.postgresql.Driver

  # --- Configuracion JPA / Hibernate ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: core
        dialect: org.hibernate.dialect.PostgreSQLDialect

# --- Configuracion Server ---
server:
  port: 8080

# --- Configuracion Logging ---
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.opticlingo: DEBUG